### ISSUE TITLE
Installation fails due to missing libraries

### ISSUE THREAD

**Issue by Franco-Sparrow** [itiligent/OpenVAS-GVM-Install#3]
Hi, thanks for such a great job making this script.

The script fails at some point due to missing libraries. Installing these dependencies before the execution of the script, will fix the error.

```bash
apt install libjson-glib-dev libksba-dev libbison-dev
```

- OS: [ Ubuntu 22.04.4 ]

**Comment by itiligent** [comment]
thankyou for the info, could you please be more specific as I cant replicate your issue.
 Which script? (Docker or soure build? - assumes source build) At what point in the script does it fail? Any error messages? Fresh install, or  dist upgrade? Othe apps or packages?

**Comment by Franco-Sparrow** [comment]
Hello

If I remember, it was compiling the openvas-scanner. I am using the script
to builf from source.

Once installed those libraries, the script install everything.

I am using the contextualized KVM image from OpenNebula Public MarketPlace,
wich is based in the Ubuntu 22.04.3 image.

**Comment by itiligent** [comment]
Ok thankyou for the extra context.
Given you are using a 3rd party image, there is potential for several variances in package contents despite claims of "based on" any particular distro. Unfortunately theres no practical way to address each and every variant without adding much more complextiy, bloat and other unintended issues.  This sort of thing comes up occasionally, but I'm glad you sorted it out and shared it with others.
Scripts are tested on native Debian and Ubuntu distros and work ok. I'm going to close without making any changes as I cant replicate this on supported base disto defaults.

**Comment by Franco-Sparrow** [comment]
@itiligent thanks to you for such a great job making this script. I have now GVM 22 without deal with the hard installation proccess.
